<Interface>:
    MDIconButton:
        icon: 'emoticon-excited'
        id:get_a_joke
        pos_hint: {'center_x': 0.4, 'center_y': 0.75}
        size_hint: None, None
        size: dp(45), dp(45)

    MDFloatingActionButton:
        id:chevron_up
        icon: 'share-variant'
        opacity: 0.9
        pos_hint:  {'center_x': 0.8, 'center_y': 0.2}
        size_hint: None, None
        size: dp(45), dp(45)
